
---
title: "Pełny proces analizy: Od danych do rankingu"
author: "Julia Milos"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pełny proces analizy: Od danych do rankingu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





```{r, include = FALSE}

knitr::opts_chunk$set(

collapse = TRUE,

comment = "#>"

)
library(FitTrackR)

#1. Wczytanie danych

data("mcda_dane_surowe")
head(mcda_dane_surowe)
#2. Definicja modelu (Składnia)

skladnia_modelu <- "

Dokladnosc =~ Tetno_Dokladnosc + Kroki_Dokladnosc + Kalorie_Dokladnosc;

Funkcjonalnosc =~ Funkcje_Zdrowotne + Funkcje_Sportowe + Funkcje_Smart;

Kompatybilnosc =~ Kompatybilnosc_Android + Kompatybilnosc_iOS;

Komfort_Jakosc =~ Wygoda_Noszenia + Jakosc_Wykonania;

Wytrzymalosc =~ Wodoodpornosc + Wytrzymalosc;

Bateria =~ Bateria_Wydajnosc;

Koszt =~ Cena_PLN

"

#3. Przetwarzanie i Rozmywanie danych

macierz_rozmyta <- przygotuj_dane_mcda(
  dane = mcda_dane_surowe, 
  skladnia = skladnia_modelu, 
  kolumna_alternatyw = "Alternatywa" 
)

# Podgląd fragmentu macierzy
print(macierz_rozmyta[1:3, 1:21])


#4. Wyznaczanie wag metodą BWM (Best-Worst Method)

# Kolejność kryteriów w macierzy:
# 1 Dokladnosc
# 2 Funkcjonalnosc
# 3 Kompatybilnosc
# 4 Komfort_Jakosc
# 5 Wytrzymalosc
# 6 Bateria
# 7 Cena


# Preferencja NAJLEPSZEGO (Dokladnosc) nad innymi (1–9):
# Dokladnosc/Dokladnosc = 1
# Dokladnosc/Funkcjonalnosc = 3
# Dokladnosc/Kompatybilnosc = 4
# Dokladnosc/Komfort_Jakosc = 5
# Dokladnosc/Wytrzymalosc = 6
# Dokladnosc/Bateria = 7
# Dokladnosc/Cena = 9

bwm_best <- c(1, 3, 4, 5, 6, 7, 9)


# Preferencja innych nad NAJGORSZYM (Cena) (1–9):
# Dokladnosc/Cena = 9
# Funkcjonalnosc/Cena = 7
# Kompatybilnosc/Cena = 6
# Komfort_Jakosc/Cena = 5
# Wytrzymalosc/Cena = 4
# Bateria/Cena = 3
# Cena/Cena = 1

bwm_worst <- c(9, 7, 6, 5, 4, 3, 1)


#5. Analiza Decyzyjna (VIKOR, TOPSIS, PROMETHEE)

criteria_type <- c(
  "max",  # Dokladnosc
  "max",  # Funkcjonalnosc
  "max",  # Kompatybilnosc
  "max",  # Komfort_Jakosc
  "max",  # Wytrzymalosc
  "max",  # Bateria
  "min"   # Koszt
)

# Fuzzy VIKOR
wynik_vikor <- fuzzy_vikor(
  decision_matrix = macierz_rozmyta,
  criteria_type = criteria_type,
  bwm_best = bwm_best,
  bwm_worst = bwm_worst
)

# Fuzzy TOPSIS
wynik_topsis <- fuzzy_topsis(
  decision_matrix = macierz_rozmyta,
  criteria_type = criteria_type,
  bwm_best = bwm_best,
  bwm_worst = bwm_worst
)

# Parametry funkcji preferencji (typ V – liniowy, dla każdego z 7 kryteriów)
preference_params <- data.frame(
  Type = rep("V", 7),
  q    = rep(0,   7),
  p    = rep(1,   7),
  s    = rep(0.5, 7)
)

# Fuzzy PROMETHEE
wynik_promethee <- fuzzy_promethee(
  decision_matrix   = macierz_rozmyta,
  criteria_type     = criteria_type,
  preference_params = preference_params,
  bwm_best          = bwm_best,
  bwm_worst         = bwm_worst
)

# Wyniki tabelaryczne
print(wynik_vikor$wyniki)
print(wynik_topsis$wyniki)
print(wynik_promethee$wyniki)

#6. Wizualizacja (Mapy Decyzyjne)

plot(wynik_vikor)
plot(wynik_topsis)
plot(wynik_promethee)

#7. Meta-Ranking (Konsensus)
meta_wynik <- fuzzy_meta_ranking(
  decision_matrix = macierz_rozmyta,
  criteria_type   = criteria_type,
  bwm_best        = bwm_best,
  bwm_worst       = bwm_worst
)

knitr::kable(meta_wynik$porownanie, caption = "Porównanie rankingów i Konsensus")
